services:
  - type: web
    name: portfolio-backend
    runtime: node
    buildCommand: npm install && npm run build && npm run db:seed
    startCommand: node dist/main.js
    envVars:
      - key: PORT
        value: 10000
